aws:
  region: "eu-west-1" 
  role_arn: "arn:aws:iam::353671347542:role/SageMakerRole"
  bucket: "thebrowntiger"

training:
  image_uri: "353671347542.dkr.ecr.eu-west-1.amazonaws.com/thesis-training:v04"
  test_size: 0.2
  random_state: 42
  use_spot: false

  xgb:
    n_estimators: 200
    max_depth: 5
    learning_rate: 0.1
